import { useState, useEffect, useRef } from 'react';
import type { SubAgent } from '../types';
import { ErrorBoundary } from './ErrorBoundary';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ReasoningStep {
  id: string;
  timestamp: number;
  type: 'thought' | 'tool_call' | 'tool_result' | 'plan' | 'revision' | 'completion' | 'error';
  label: string;
  detail?: string;
  toolName?: string;
  toolInput?: string;
  toolOutput?: string;
  durationMs?: number;   // how long this step took
  tokens?: number;       // tokens consumed in this step
  parentId?: string;     // for nested reasoning
  children?: ReasoningStep[];
}

interface Props {
  sessionKey: string;
  subAgents: SubAgent[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatAbsTime(ts: number): string {
  return new Date(ts).toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit', fractionalSecondDigits: 2 });
}

function formatRelTime(ts: number): string {
  const diff = Date.now() - ts;
  const secs = Math.floor(diff / 1000);
  if (secs < 5) return 'just now';
  if (secs < 60) return `${secs}s ago`;
  const mins = Math.floor(secs / 60);
  return `${mins}m ago`;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60000).toFixed(1)}m`;
}

// ─── Step type config ─────────────────────────────────────────────────────────

const STEP_CONFIG: Record<ReasoningStep['type'], { icon: string; color: string; bgColor: string; borderColor: string; label: string }> = {
  thought:      { icon: '💭', color: 'var(--yellow)',  bgColor: 'rgba(251,191,36,0.06)',  borderColor: 'rgba(251,191,36,0.25)',  label: 'Thought' },
  plan:         { icon: '📋', color: 'var(--cyan)',    bgColor: 'rgba(34,211,238,0.06)',   borderColor: 'rgba(34,211,238,0.25)',   label: 'Plan' },
  tool_call:    { icon: '🔧', color: 'var(--accent)',  bgColor: 'rgba(59,122,255,0.08)',  borderColor: 'rgba(59,122,255,0.3)',   label: 'Tool Call' },
  tool_result:  { icon: '📥', color: 'var(--green)',   bgColor: 'rgba(52,211,153,0.06)',  borderColor: 'rgba(52,211,153,0.25)',  label: 'Result' },
  revision:     { icon: '✏️', color: 'var(--orange)',   bgColor: 'rgba(251,146,60,0.06)',  borderColor: 'rgba(251,146,60,0.25)',  label: 'Revision' },
  completion:   { icon: '✅', color: 'var(--green)',   bgColor: 'rgba(52,211,153,0.06)',  borderColor: 'rgba(52,211,153,0.25)',  label: 'Done' },
  error:        { icon: '✕',  color: 'var(--red)',     bgColor: 'rgba(248,113,113,0.08)', borderColor: 'rgba(248,113,113,0.3)',  label: 'Error' },
};

// ─── Demo/simulated reasoning generator ──────────────────────────────────────

/** Generates a realistic demo reasoning trace for a session */
function generateDemoTrace(sa: SubAgent): ReasoningStep[] {
  const now = Date.now();
  const start = sa.startedAt || (now - 120_000);
  const steps: ReasoningStep[] = [];
  let seq = 0;
  const push = (type: ReasoningStep['type'], label: string, detail?: string, durMs?: number, extra?: Partial<ReasoningStep>): ReasoningStep => ({
    id: `step-${seq++}`,
    timestamp: steps.length === 0 ? start : (steps[steps.length - 1].timestamp + (durMs ?? 800) + Math.floor(Math.random() * 400)),
    type,
    label,
    detail,
    durationMs: durMs ?? (300 + Math.floor(Math.random() * 1200)),
    ...extra,
  });

  steps.push(push('thought', 'Reading task', `Task: "${sa.taskName || 'No description'}"`, 420));
  steps.push(push('plan', 'Planning approach', `Will use ${sa.runtime} runtime to process this request`, 680));
  steps.push(push('thought', 'Checking context', 'Memory check: recent work found in MEMORY.md', 350));

  // Tool calls
  const tools = ['memory_search', 'exec', 'read', 'web_fetch', 'write'];
  const numTools = 2 + Math.floor(Math.random() * 4);
  for (let i = 0; i < numTools; i++) {
    const tool = tools[Math.floor(Math.random() * tools.length)];
    const toolInputs: Record<string, string> = {
      memory_search: `{"query": "recent ${sa.taskName?.split(' ').slice(0, 2).join(' ') ?? 'work'}"}`,
      exec: '{"command": "git status"}',
      read: '{"path": "/Users/jens/.openclaw/workspace/AGENTS.md"}',
      web_fetch: '{"url": "https://api.github.com/repos/openclaw/openclaw"}',
      write: '{"path": "/tmp/output.md", "content": "# Report\\n\\nGenerated by agent"}',
    };
    const toolOutputs: Record<string, string> = {
      memory_search: '{"results": [{"id": "abc", "text": "Jens worked on..."}]}',
      exec: '{"stdout": "On branch main\\nStatus: clean", "exitCode": 0}',
      read: '{"lines": 45, "truncated": false}',
      web_fetch: '{"status": 200, "chars": 2847}',
      write: '{"bytesWritten": 124}',
    };
    steps.push(push('tool_call', `Call: ${tool}`, tool[0].toUpperCase() + tool.slice(1), 150 + Math.floor(Math.random() * 300), {
      toolName: tool,
      toolInput: toolInputs[tool] ?? '{}',
    }));
    steps.push(push('tool_result', `Result: ${tool}`, `${tool} completed successfully`, 200 + Math.floor(Math.random() * 600), {
      toolName: tool,
      toolOutput: toolOutputs[tool] ?? '{"ok": true}',
    }));
  }

  steps.push(push('thought', 'Synthesizing response', 'Combining gathered information into final answer', 920));
  steps.push(push('revision', 'Refining output', 'Improving clarity based on context constraints', 540));
  steps.push(push('completion', 'Task complete', 'All objectives achieved', 310));

  return steps;
}

// ─── Flattened tree with depth ────────────────────────────────────────────────

interface FlatStep {
  step: ReasoningStep;
  depth: number;
}

function flatten(steps: ReasoningStep[], depth = 0): FlatStep[] {
  const result: FlatStep[] = [];
  for (const step of steps) {
    result.push({ step, depth });
    if (step.children?.length) {
      result.push(...flatten(step.children, depth + 1));
    }
  }
  return result;
}

// ─── Step entry ───────────────────────────────────────────────────────────────

interface StepEntryProps {
  step: ReasoningStep;
  depth: number;
  isNew: boolean;
  onCopy: (text: string) => void;
}

function StepEntry({ step, depth, isNew, onCopy }: StepEntryProps) {
  const [expanded, setExpanded] = useState(false);
  const cfg = STEP_CONFIG[step.type];
  const hasDetail = !!(step.detail || step.toolName || step.toolInput || step.toolOutput || step.durationMs);

  const handleCopy = (e: React.MouseEvent) => {
    e.stopPropagation();
    const text = [
      `[${step.type.toUpperCase()}] ${step.label}`,
      step.detail ? `Detail: ${step.detail}` : null,
      step.toolName ? `Tool: ${step.toolName}` : null,
      step.toolInput ? `Input: ${step.toolInput}` : null,
      step.toolOutput ? `Output: ${step.toolOutput}` : null,
      step.durationMs ? `Duration: ${formatDuration(step.durationMs)}` : null,
    ].filter(Boolean).join('\n');
    onCopy(text);
  };

  return (
    <div
      className={`rt-step${isNew ? ' rt-step--new' : ''}`}
      style={{
        marginLeft: `${depth * 16}px`,
        borderLeft: `2px solid ${cfg.borderColor}`,
        background: isNew ? cfg.bgColor : 'transparent',
        borderRadius: '0 6px 6px 0',
        marginBottom: '2px',
        transition: 'background 0.3s ease',
      }}
    >
      <div
        className="rt-step-row"
        onClick={() => hasDetail && setExpanded(v => !v)}
        style={{
          display: 'flex',
          alignItems: 'flex-start',
          gap: '8px',
          padding: '6px 10px',
          cursor: hasDetail ? 'pointer' : 'default',
          opacity: step.type === 'tool_result' ? 0.75 : 1,
        }}
      >
        {/* Connector dot */}
        <span style={{
          width: '8px', height: '8px', borderRadius: '50%',
          background: cfg.color, flexShrink: 0, marginTop: '4px',
          boxShadow: `0 0 6px ${cfg.color}`,
        }} />

        {/* Icon */}
        <span style={{ fontSize: '12px', flexShrink: 0 }}>{cfg.icon}</span>

        {/* Content */}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}>
            <span style={{ fontSize: '11px', fontWeight: 600, color: cfg.color, fontFamily: "'Space Grotesk', sans-serif" }}>
              {step.label}
            </span>
            {step.durationMs && (
              <span style={{
                fontSize: '9px', fontFamily: "'JetBrains Mono', monospace",
                color: step.durationMs > 2000 ? 'var(--yellow)' : 'var(--text-muted)',
                background: 'var(--bg-input)', border: '1px solid var(--border)',
                borderRadius: '6px', padding: '1px 5px',
              }}>
                {formatDuration(step.durationMs)}
              </span>
            )}
            {step.toolName && (
              <span style={{
                fontSize: '9px', fontFamily: "'JetBrains Mono', monospace",
                color: 'var(--accent)', background: 'rgba(59,122,255,0.1)',
                border: '1px solid rgba(59,122,255,0.25)',
                borderRadius: '6px', padding: '1px 5px',
              }}>
                {step.toolName}
              </span>
            )}
            {step.tokens !== undefined && (
              <span style={{ fontSize: '9px', fontFamily: "'JetBrains Mono', monospace", color: 'var(--green)' }}>
                {step.tokens.toLocaleString()} tok
              </span>
            )}
          </div>
          {step.detail && (
            <div style={{
              fontSize: '10px', color: 'var(--text-secondary)',
              marginTop: '2px', fontFamily: "'Space Grotesk', sans-serif",
              overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
              maxWidth: '420px',
            }}>
              {step.detail}
            </div>
          )}
        </div>

        {/* Meta */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '4px', flexShrink: 0 }}>
          <span style={{ fontSize: '9px', fontFamily: "'JetBrains Mono', monospace", color: 'var(--text-muted)' }}>
            {formatRelTime(step.timestamp)}
          </span>
          {hasDetail && (
            <span style={{
              fontSize: '8px', color: 'var(--text-muted)',
              transition: 'transform 0.2s',
              transform: expanded ? 'rotate(180deg)' : 'rotate(0deg)',
            }}>
              ▼
            </span>
          )}
          <button
            onClick={handleCopy}
            title="Copy step details"
            style={{
              background: 'transparent', border: 'none', cursor: 'pointer',
              fontSize: '10px', color: 'var(--text-muted)', padding: '0 2px',
              borderRadius: '3px',
            }}
            onMouseEnter={e => (e.currentTarget.style.color = 'var(--accent)')}
            onMouseLeave={e => (e.currentTarget.style.color = 'var(--text-muted)')}
          >
            📋
          </button>
        </div>
      </div>

      {/* Expanded detail */}
      {expanded && hasDetail && (
        <div style={{
          margin: '0 10px 8px 34px',
          background: 'var(--bg-input)',
          border: '1px solid var(--border)',
          borderRadius: '8px',
          padding: '10px 12px',
          display: 'flex',
          flexDirection: 'column',
          gap: '6px',
        }}>
          {step.detail && (
            <div>
              <div style={{ fontSize: '9px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '3px' }}>Detail</div>
              <div style={{ fontSize: '11px', color: 'var(--text-primary)', fontFamily: "'Space Grotesk', sans-serif", lineHeight: 1.5 }}>{step.detail}</div>
            </div>
          )}
          {step.toolName && (
            <div>
              <div style={{ fontSize: '9px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '3px' }}>Tool</div>
              <div style={{ fontSize: '11px', color: 'var(--accent)', fontFamily: "'JetBrains Mono', monospace" }}>{step.toolName}</div>
            </div>
          )}
          {step.toolInput && (
            <div>
              <div style={{ fontSize: '9px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '3px' }}>Input</div>
              <div style={{
                fontSize: '10px', color: 'var(--text-secondary)', fontFamily: "'JetBrains Mono', monospace",
                background: 'var(--bg-deep)', border: '1px solid var(--border)',
                borderRadius: '6px', padding: '6px 8px', maxHeight: '120px', overflowY: 'auto',
                wordBreak: 'break-all', whiteSpace: 'pre-wrap',
              }}>
                {(() => {
                  try { return JSON.stringify(JSON.parse(step.toolInput!), null, 2); }
                  catch { return step.toolInput; }
                })()}
              </div>
            </div>
          )}
          {step.toolOutput && (
            <div>
              <div style={{ fontSize: '9px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '3px' }}>Output</div>
              <div style={{
                fontSize: '10px', color: 'var(--green)', fontFamily: "'JetBrains Mono', monospace",
                background: 'var(--bg-deep)', border: '1px solid var(--border)',
                borderRadius: '6px', padding: '6px 8px', maxHeight: '120px', overflowY: 'auto',
                wordBreak: 'break-all', whiteSpace: 'pre-wrap',
              }}>
                {(() => {
                  try { return JSON.stringify(JSON.parse(step.toolOutput!), null, 2); }
                  catch { return step.toolOutput; }
                })()}
              </div>
            </div>
          )}
          <div style={{ display: 'flex', gap: '12px' }}>
            {step.timestamp && (
              <div>
                <div style={{ fontSize: '9px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '3px' }}>Time</div>
                <div style={{ fontSize: '10px', color: 'var(--text-secondary)', fontFamily: "'JetBrains Mono', monospace" }}>
                  {formatAbsTime(step.timestamp)}
                </div>
              </div>
            )}
            {step.durationMs && (
              <div>
                <div style={{ fontSize: '9px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '3px' }}>Duration</div>
                <div style={{ fontSize: '10px', color: step.durationMs > 2000 ? 'var(--yellow)' : 'var(--text-secondary)', fontFamily: "'JetBrains Mono', monospace" }}>
                  {formatDuration(step.durationMs)}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Stats bar ────────────────────────────────────────────────────────────────

function TraceStats({ steps, sessionKey }: { steps: ReasoningStep[]; sessionKey: string }) {
  const counts: Record<string, number> = {};
  steps.forEach(s => { counts[s.type] = (counts[s.type] ?? 0) + 1; });
  const totalMs = steps.reduce((sum, s) => sum + (s.durationMs ?? 0), 0);
  const toolCalls = steps.filter(s => s.type === 'tool_call').length;
  const toolResults = steps.filter(s => s.type === 'tool_result').length;
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap',
      fontSize: '10px', fontFamily: "'Space Grotesk', sans-serif",
    }}>
      <span style={{ display: 'flex', alignItems: 'center', gap: '4px', color: 'var(--text-muted)' }}>
        <span style={{ fontSize: '8px' }}>◉</span> LIVE
      </span>
      <span style={{ color: 'var(--text-muted)' }}>{steps.length} steps</span>
      {toolCalls > 0 && (
        <span style={{ color: 'var(--accent)', fontWeight: 600 }}>
          🔧 {toolCalls} tool call{toolCalls !== 1 ? 's' : ''}
        </span>
      )}
      {toolResults > 0 && (
        <span style={{ color: 'var(--green)' }}>
          📥 {toolResults} result{toolResults !== 1 ? 's' : ''}
        </span>
      )}
      {totalMs > 0 && (
        <span style={{ color: 'var(--text-muted)', fontFamily: "'JetBrains Mono', monospace" }}>
          ⏱ {formatDuration(totalMs)} total
        </span>
      )}
      <span style={{ fontSize: '9px', fontFamily: "'JetBrains Mono', monospace", color: 'var(--text-muted)', marginLeft: 'auto' }}>
        {sessionKey.slice(0, 12)}…
      </span>
    </div>
  );
}

// ─── Main Component ────────────────────────────────────────────────────────────

export default function ReasoningTrace({ sessionKey, subAgents }: Props) {
  const sa = subAgents.find(s => s.sessionKey === sessionKey);

  // Simulated reasoning steps (in a real impl, these would come from gateway events)
  const [steps, setSteps] = useState<ReasoningStep[]>(() => sa ? generateDemoTrace(sa) : []);
  const [copied, setCopied] = useState(false);
  const [filterType, setFilterType] = useState<ReasoningStep['type'] | 'all'>('all');
  const [arrivedCount, setArrivedCount] = useState(0);
  const prevLenRef = useRef(steps.length);

  // Refresh steps when session changes
  useEffect(() => {
    if (sa) {
      setSteps(generateDemoTrace(sa));
      setArrivedCount(0);
      prevLenRef.current = 0;
    }
  }, [sessionKey]);

  // Track new arrivals
  useEffect(() => {
    if (steps.length > prevLenRef.current) {
      setArrivedCount(n => n + (steps.length - prevLenRef.current));
    }
    prevLenRef.current = steps.length;
  }, [steps.length]);

  // Tick relative timestamps
  const [, tick] = useState(0);
  useEffect(() => {
    const t = setInterval(() => tick(n => n + 1), 10000);
    return () => clearInterval(t);
  }, []);

  const handleCopy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* silent */ }
  };

  const handleCopyAll = async () => {
    const text = steps.map(s =>
      `[${s.timestamp}] [${s.type.toUpperCase()}] ${s.label}${s.detail ? `\n  ${s.detail}` : ''}${s.toolName ? `\n  tool: ${s.toolName}` : ''}${s.durationMs ? `\n  duration: ${formatDuration(s.durationMs)}` : ''}`
    ).join('\n');
    await handleCopy(text);
  };

  const flatSteps = flatten(steps);
  const filtered = filterType === 'all' ? flatSteps : flatSteps.filter(({ step }) => step.type === filterType);

  const types: (ReasoningStep['type'] | 'all')[] = ['all', 'thought', 'plan', 'tool_call', 'tool_result', 'revision', 'completion', 'error'];

  if (!sa) {
    return (
      <div style={{
        padding: '20px', textAlign: 'center', color: 'var(--text-muted)',
        fontFamily: "'Space Grotesk', sans-serif", fontSize: '12px',
      }}>
        Session not found
      </div>
    );
  }

  return (
    <ErrorBoundary name="ReasoningTrace">
      <div className="reasoning-trace-panel" style={{
        display: 'flex', flexDirection: 'column',
        height: '100%', fontFamily: "'Space Grotesk', sans-serif",
      }}>
        {/* Header */}
        <div style={{
          padding: '10px 14px',
          borderBottom: '1px solid var(--border)',
          background: 'var(--bg-card)',
          display: 'flex', flexDirection: 'column', gap: '8px',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <span style={{ fontSize: '14px' }}>💭</span>
              <span style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text-primary)' }}>
                Reasoning Trace
              </span>
              <span style={{
                fontSize: '9px', fontFamily: "'JetBrains Mono', monospace",
                color: 'var(--accent)', background: 'rgba(59,122,255,0.1)',
                border: '1px solid rgba(59,122,255,0.2)',
                borderRadius: '8px', padding: '1px 6px',
              }}>
                {sa.runtime === 'pi' ? 'Pi' : sa.runtime?.charAt(0).toUpperCase() + sa.runtime?.slice(1)} runtime
              </span>
            </div>
            <div style={{ display: 'flex', gap: '6px' }}>
              <button
                onClick={handleCopyAll}
                title="Copy entire reasoning trace"
                style={{
                  background: copied ? 'rgba(52,211,153,0.15)' : 'rgba(59,122,255,0.08)',
                  border: `1px solid ${copied ? 'rgba(52,211,153,0.3)' : 'rgba(59,122,255,0.2)'}`,
                  borderRadius: '8px', padding: '3px 10px',
                  fontSize: '10px', fontFamily: "'Space Grotesk', sans-serif",
                  color: copied ? 'var(--green)' : 'var(--accent)',
                  cursor: 'pointer', transition: 'all 0.2s',
                }}
              >
                {copied ? '✓ Copied' : '📋 Copy All'}
              </button>
            </div>
          </div>
          <TraceStats steps={steps} sessionKey={sa.sessionKey} />
        </div>

        {/* Filter bar */}
        <div style={{
          display: 'flex', gap: '4px', padding: '6px 14px',
          borderBottom: '1px solid var(--border)',
          overflowX: 'auto', flexShrink: 0,
        }}>
          {types.map(type => {
            const cfg = type === 'all' ? { icon: '◉', color: 'var(--accent)', label: 'All' } : STEP_CONFIG[type];
            const count = type === 'all' ? steps.length : steps.filter(s => s.type === type).length;
            const isActive = filterType === type;
            return (
              <button
                key={type}
                onClick={() => setFilterType(type as ReasoningStep['type'] | 'all')}
                style={{
                  background: isActive ? `${cfg.color}18` : 'transparent',
                  border: `1px solid ${isActive ? `${cfg.color}44` : 'var(--border)'}`,
                  borderRadius: '10px', padding: '2px 8px',
                  fontSize: '10px', fontFamily: "'Space Grotesk', sans-serif",
                  color: isActive ? cfg.color : 'var(--text-muted)',
                  fontWeight: isActive ? 600 : 400,
                  cursor: 'pointer', transition: 'all 0.15s',
                  whiteSpace: 'nowrap',
                  boxShadow: isActive ? `0 0 6px ${cfg.color}22` : 'none',
                }}
              >
                {cfg.icon} {count > 0 && count}
              </button>
            );
          })}
        </div>

        {/* Steps list */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '6px 14px' }}>
          {filtered.length === 0 ? (
            <div style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)', fontSize: '11px' }}>
              No reasoning steps yet
            </div>
          ) : (
            filtered.map(({ step, depth }, i) => (
              <StepEntry
                key={step.id}
                step={step}
                depth={depth}
                isNew={i < arrivedCount && arrivedCount > 0}
                onCopy={handleCopy}
              />
            ))
          )}
        </div>

        {/* Footer */}
        <div style={{
          padding: '6px 14px',
          borderTop: '1px solid var(--border)',
          fontSize: '9px', fontFamily: "'JetBrains Mono', monospace",
          color: 'var(--text-muted)',
          display: 'flex', justifyContent: 'space-between',
        }}>
          <span>{filtered.length} step{filtered.length !== 1 ? 's' : ''}{filterType !== 'all' ? ` (${filterType})` : ''}</span>
          <span>Click any step to expand details</span>
        </div>
      </div>
    </ErrorBoundary>
  );
}
